config/routes.rb
SmilestonesApp::Application.routes.draw do

  resource :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :children do
    resources :milestones
  end

  root 'sessions#new'

end

app/models/child.rb
class Child
  include Mongoid::Document
  field :name, type: String
  field :birth_date, type: Date
  embeds_many :milestones
  belongs_to :user
end

app/models/image.rb
class Image
  include Mongoid::Document
  has_many :milestones
end

app/models/milestone.rb
class Milestone
  include Mongoid::Document
  include Mongoid::Paperclip

  has_mongoid_attached_file :picture
  #    :styles => {
  #     :thumb => "100x100#",   # Centrally cropped
  #     :small  => "150x150>"}  # limit size

  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  field :date, type: Date
  field :notes, type: String
  field :name, type: String
  field :custom, type: String
  embedded_in :child

  def computed_name
    if self.name == "Other"
      self.custom_name
    else
      self.name
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :hashed_password, type: String
  has_many :children

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    self.hashed_password = BCrypt::Password.create(new_password)
  end

  def authenticate(test_password)
    if BCrypt::Password.new(self.hashed_password) == test_password
      self
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController

  before_action :authenticate_user

  def index
    @children = current_user.children.all
  end

  def show
    @child = Child.find(params[:id])
    @milestones = @child.milestones
  end

  def new
    @child = current_user.children.build
  end

  def create
    @child = Child.new(params.require(:child).permit(:name, :birth_date, :user_id, :milestones =>[]))
    if @child.save
        flash[:success] = "Success! You added another child."
        redirect_to children_path
      else
        render 'new'
    end
  end


  def edit
    @child = Child.find(params[:id])
  end

  def update
    @child = Child.find(params[:id])
    if @child.update(params.require(:child).permit(:name, :birth_date, :user_id, :milestones =>[]))
      redirect_to child_path
    else
      render 'edit'
    end
  end

  def destroy
    @child = Child.find(params[:id])
    if @child.destroy
        flash[:success] = "Your child has been grounded from the site."
        redirect_to children_path
      else
        render 'new'
      end
    end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController


def new
  @milestone = Milestone.new
  @child = Child.find(params[:child_id])
  @type = ["Choose a Milestone", "first steps", "first birthday", "first day of school", "wedding"]
end

def create
  @child = Child.find(params[:child_id])
  @milestone = @child.milestones.new(params.require(:milestone).permit(:date, :notes, :name, :custom, :picture))
  if @milestone.save
    flash[:success] = "You updated your milestones!"
    redirect_to child_path(@child)
  else
    render 'new'
  end
end


def show
  # @milestone = Milestone.find(params[:id])
end

def edit
  child = Child.find(params[:child_id])
  @milestone = child.milestones.find(params[:id])
end

def destroy
  child = Child.find(params[:child_id])
  @milestone = child.milestones.find(params[:id])
  if @milestone.destroy
    flash[:success] = "Milestone deleted."
    redirect_to child_path(child)
  else
    render 'new'
  end
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      flash[:success] = "Welcome!"
      redirect_to children_path
    end

  end

  def destroy
    session.delete(:remember_token)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have now signed up! Login below to begin creating milestones..."
      redirect_to :root
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

protected

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

# current_user sets up who is logging in. use :current_user when we need to access something throughout the app. use @current_user when defining for a specific section of code. or/= means
  def current_user
    @current_user ||= session[:remember_token] && User.find(session[:remember_token])
  end

  def authenticate_user
    if !current_user
      redirect_to new_sessions_path
    end
  end

end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/children/_children.html.erb
<!-- partial used by edit & new views in children folder -->

<div class="partial_form">

  <%= form_for @child do |c| %>
    <%= c.hidden_field :user_id, :value => current_user.id %>
    <%= c.text_field :name, placeholder: "Name", class: 'form-control' %>
    <br />
    <%= c.date_field :birth_date, placeholder: "Birthdate", class: 'form-control' %>
    <br />
    <%= c.submit "Update!", class: "btn btn-primary pull-right" %>

  <% end %>

</div>

app/views/children/edit.html.erb
<div class="container-fluid">
  <h2>Edit a Child</h2>
  <br />

  <!-- rendering partial called _children.html.erb -->
  <%= render "children" %>

  <%= link_to 'Back', :children %>
</div>

app/views/children/index.html.erb
<!-- Adding children is the first step in the process. Next is adding milestones for each child. Children are only viewable by the user that created them. -->

<div class="container-fluid">
  <h2>My Children</h2>
  <br />
  <a class="btn btn-primary" <%= link_to 'Add a new child', new_child_path %></a>
  <br />
  <div "class=table-responsive">
    <table class="table table-condensed">

        <% @children.each do |c| %>
          <tr>
            <td><%= c.name %></td>
            <td><%= link_to "See Child Info", child_path(c) %></td>
            <td><%= link_to 'Edit', edit_child_path(c) %></td>
            <td><%= link_to 'Delete', child_path(c), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <br />
        <% end %>
    </table>
  </div>


  <hr>
  <!-- <a class="btn btn-primary"</a> -->
  <%= link_to 'Back', :root %>
</div>

app/views/children/new.html.erb
<div class="container-fluid">
  <h2>Add a New Child</h2>

  <!-- rendering partial called _children.html.erb -->
  <%= render "children" %>

  <%= link_to 'Back', :children %>
</div>

app/views/children/show.html.erb
<!-- Milestones are associated with children. Images are added to milestones. Future functionality will include videos that are linked to each milestone created. -->

<div class="container-fluid">
  <h2><%= @child.name %>'s Milestones</h2>

  <h3>Birthday: <%= @child.birth_date.strftime("%m/%d/%Y") %></h3>
  <br />
  <a class="btn btn-primary" <%= link_to 'Add a new milestone', new_child_milestone_path(@child) %></a>
  <br />
  <div "class=table-responsive">
    <table class="table table-condensed">
      <% @milestones.each do |m| %>
        <tr>
          <td><%= m.name %></td>
          <td class="image">
            <!-- image tag pulls the image using the "image" CSS styles, set to thumbnail size. link_to links to original-size view of the picture -->
            <%#= link_to m.picture.url(:original) do %>
            <%= image_tag(m.picture.url) %>
            <%# end %>
          </td>

  <!-- Placeholder for editing function      <td><= link_to 'Edit', edit_child_milestone_path(@child, m) %></td> -->

          <td><%= link_to 'Delete', child_milestone_path(@child, m), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <br />
      <% end %>
    </table>
  </div>
  <hr>

  <!-- Placeholder to Create a Smilestone link<a class="btn btn-primary pull right" <%#= link_to 'Create a SMILESTONE' %></a> -->

  <%= link_to 'Back', :children %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmilestonesApp</title>
  <link href='http://fonts.googleapis.com/css?family=The+Girl+Next+Door|Varela+Round' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to "Smilestones", :root %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if !current_user %>
            <li><a href="#features">Features</a></li>
            <li><a href="#about">About</a></li>
        <% end %>
<!--         <li><a href="#features">Features</a></li>
        <li><a href="#about">About</a></li> -->

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "My Milestones", children_path %></li>
        <% if current_user %>
          <li><%= link_to "Sign Out", sessions_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- <br /> -->

<body>
<!-- <div class="container"> -->
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
<!-- </div> -->
</body>
</html>

app/views/milestones/new.html.erb
<!-- Creating a milestone is the key step in the process of building an association between the photos and videos that are uploaded. -->

<div class="container-fluid">
  <h2>Create a new milestone</h2>
  <br />
  <br />
  <%= form_for [@child, @milestone] do |m| %>
  <!-- collection_select includes: field/attribute, variable defined in the controller, value to be stored (converted to string), value want displayed(also converted to string)  -->
    <%= m.collection_select :name, @type, :to_s, :to_s %>
    <br />
    <br />
    <%= m.date_field :date, placeholder: "Date", class: 'form-control' %>
    <br />
    <%= m.text_field :notes, placeholder: "Add Notes...", class: 'form-control' %>
    <br />
    <%= m.file_field :picture %>
    <br />
    <%= m.submit "Update!", class: "btn btn-primary pull-right"%>
  <% end %>
  <br />
  <hr>
  <%= link_to 'Back', :children %>
</div>

app/views/users/new.html.erb
<div class="container-fluid">
  <h2>New user sign-up</h2>
  <br />
  <%= form_for @user do |f| %>
    Name: <%= f.text_field :name %>
    Email: <%= f.text_field :email %>
    Password: <%= f.password_field :password %>
    <%= f.submit %>
  <% end %>
</div>